---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	insurance_node(insurance_node)
	report_node(report_node)
	advisor_node(advisor_node)
	pharmacy_node(pharmacy_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	router -.-> advisor_node;
	router -.-> clinic_node\3aemergency_gate;
	router -.-> insurance_node;
	router -.-> pharmacy_node;
	router -.-> report_node;
	advisor_node --> __end__;
	clinic_node\3a__end__ --> __end__;
	insurance_node --> __end__;
	pharmacy_node --> __end__;
	report_node --> __end__;
	subgraph clinic_node
	clinic_node\3aemergency_gate(emergency_gate)
	clinic_node\3aextract_symptoms(extract_symptoms)
	clinic_node\3acheck_sufficiency(check_sufficiency)
	clinic_node\3aask_followup(ask_followup)
	clinic_node\3aawait_answer(await_answer)
	clinic_node\3aconclude(conclude)
	clinic_node\3a__end__(<p>__end__</p>)
	clinic_node\3aask_followup --> clinic_node\3aawait_answer;
	clinic_node\3aawait_answer --> clinic_node\3aextract_symptoms;
	clinic_node\3acheck_sufficiency -.-> clinic_node\3aask_followup;
	clinic_node\3acheck_sufficiency -.-> clinic_node\3aconclude;
	clinic_node\3aemergency_gate -.-> clinic_node\3a__end__;
	clinic_node\3aemergency_gate -.-> clinic_node\3aextract_symptoms;
	clinic_node\3aextract_symptoms --> clinic_node\3acheck_sufficiency;
	clinic_node\3aconclude --> clinic_node\3a__end__;
	end
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
